#!/bin/sh
case "$1" in
	start)
		echo "Starting aesdsocket in daemon mode"
		start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
		/usr/bin/aesdchar_load aesdchar
		;;
	stop)
		echo "Stopping aesdsocket"
		start-stop-daemon -K -n aesdsocket
		/usr/bin/aesdchar_unload aesdchar
		# signal delivered is TERM as default
		;;
	*)
		echo "usage: $0 {start|stop}"
		exit 1
		;;
esac

exit 0